name: 'Accion calculadora'
description: 'sumar dos números pasados por el workflow'
inputs:
  num1:
    description: 'primer número'
    required: true

  num2:
    description: 'segundo número'
    required: true

outputs:
  suma:
    description: 'suma de los dos inputs'
    value: ${{steps.resultado_suma.outputs.suma}}

  resta:
    description: 'resta de los dos inputs'
    value: ${{steps.resultado_resta.outputs.resta}}

runs:
  using: 'composite'
  steps:
    - name: resultado suma
      id: resultado_suma
      run: |
        echo ${{inputs.num1}} + ${{inputs.num2}}
        echo suma=$((${{inputs.num1}} + ${{inputs.num2}}))
        RESULTADO_SUMA=$((${{inputs.num1}} + ${{inputs.num2}}))
        echo resultado: $RESULTADO_SUMA
        echo "::set-output name=suma::$RESULTADO_SUMA"
      shell: bash

    - name: resultado resta
      id: resultado_resta
      run: |
        echo ${{inputs.num1}} - ${{inputs.num2}}
        echo resta=$((${{inputs.num1}} - ${{inputs.num2}}))
        RESULTADO_RESTA=$((${{inputs.num1}} - ${{inputs.num2}}))
        echo resultado: $RESULTADO_RESTA
        echo "::set-output name=resta::$RESULTADO_RESTA"
        echo $GITHUB_ACTION
      shell: bash
