name: 'Accion invocada'
description: 'imprimir Hola $nombre'
inputs:
  nombre:
    description: 'mi nombre'
    required: true
    default: ' '
outputs:
  nombre:
  description: 'mi nombre'
  required: true
  defautl: ' '
  
runs:
  using: 'composite'
  steps:
    - run: echo Hola ${{ inputs.nombre }}.
      shell: bash
    
