name: 'Accion invocada'
description: 'imprimir Hola $nombre'
inputs:
  nombre:
    description: 'mi nombre'
    required: true
outputs:
  nombre:
    description: 'mi nombre'
    value: ${{ inputs.nombre }}
  
runs:
  using: 'composite'
  steps:
    - run: echo Hola ${{ inputs.nombre }}.
      shell: bash
    
