name: 'Accion invocada'
description: 'imprimir Hola $nombre'
inputs:
  nombre:
    description: 'mi nombre'
    required: true
    default: 'Pablo'
runs:
  using: 'composite'
  steps:
    - run: echo Hola ${{ inputs.nombre }}.
      shell: bash
    
