# This is a basic workflow to help you get started with Actions

name: Prueba ifs

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches:
      - "main"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
        node: [6, 8, 10]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-node@v1
        with:
          ref: 'main'
          node-version: ${{matrix.node}}

      - uses: actions/checkout@v2

      - name: 'event name'
        run: |
          echo "pull request: ${{  github.event_name }} "

      - name: 'json pull request event'
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "pull request: ${{ toJson(github.event.pull_request) }} "

      - name: 'if PR se ha mergeado'
        if: ${{ ( github.event_name == 'pull_request' && github.event.pull_request.merged == true ) }}
        run: |
          echo "PR mergeada"

      - name: 'if PR NO se ha mergeado'
        if: ${{ ( github.event_name == 'pull_request' && github.event.pull_request.merged == false ) }}
        run: |
          echo "PR NO mergeada"
          
      - name: 'if PR se ha abierto'
        if: ${{ ( github.event_name == 'pull_request' && github.event.pull_request.state == 'open' ) }}
        run: |
          echo "PR abierta"
        

      # Runs a single command using the runners shell
      - name: Run a one-line script
        if: ${{ github.event.pull_request.opened == true }}
        run: |
          echo Hello, Sonia!
          pwd
          ls 
          dia=$(date)
          echo "dia: $dia"
          echo "dia=${dia}" >> $GITHUB_ENV

      - name: Use of IF
        run: |
          if [ $(echo ${{ env.dia }} | grep Mon | wc -l) -eq 1 ]
          then
            echo "Hoy es lunes"
          else
            echo "Hoy no es lunes"
          fi
      
      - name: Suma
        id: suma
        uses: ./actions/actionsuma
        with:
          num1: 5
          num2: 3
    
      - name: Run an action with app.js
        id: js
        uses: ./actions/actionjs

      - name: Run an action with app.js
        id: calc
        uses: ./actions/actioncalcular
